improve the build script

diff --git a/cpsatst b/cpsatst
--- a/cpsatst
+++ b/cpsatst
@@ -1,8 +1,8 @@
 #! /bin/sh
 
 # This script runs the test suite, and then reduces the data for
-# inspection.  If make fails, something is very wrong.  If differences
-# appear in the output, there might be a problem.
+# inspection.  If you see "cpsa4 failed", something is very wrong.  If
+# differences appear in the output, there might be a problem.
 
 # The following scripts in the tst directory might also serve as a
 # template for your needs, but probably not.  Look at doc/cpsa.mk
@@ -17,28 +17,28 @@ for i in tst/*.scm
 do
     b=tst/`basename "$i" .scm`
     echo cpsa4 ${CPSAFLAGS} -o "$b.txt" "$i"
-    cabal run cpsa4 -- ${CPSAFLAGS} -o "$b.txt" "$i" || echo cpsa4 failed.
+    cabal run cpsa4 -v0 -- ${CPSAFLAGS} -o "$b.txt" "$i" || echo cpsa4 failed.
     echo cpsa4diff "$b.tst" "$b.txt"
-    cabal run cpsa4diff -- "$b.tst" "$b.txt"
+    cabal run cpsa4diff -v0 -- "$b.tst" "$b.txt"
     echo cpsa4graph -o "$b.xhtml" "$b.txt"
-    cabal run cpsa4graph -- -o "$b.xhtml" "$b.txt"
+    cabal run cpsa4graph -v0 -- -o "$b.xhtml" "$b.txt"
     echo cpsa4shapes -o "${b}_shapes.txt" "$b.txt"
-    cabal run cpsa4shapes -- -o "${b}_shapes.txt" "$b.txt"
+    cabal run cpsa4shapes -v0 -- -o "${b}_shapes.txt" "$b.txt"
     echo cpsa4graph -o "${b}_shapes.xhtml" "${b}_shapes.txt"
-    cabal run cpsa4graph -- -o "${b}_shapes.xhtml" "${b}_shapes.txt"
+    cabal run cpsa4graph -v0 -- -o "${b}_shapes.xhtml" "${b}_shapes.txt"
 done
 
 for i in tst/*.lsp
 do
     b=tst/`basename "$i" .lsp`
     echo cpsa4 ${CPSAFLAGS} -o "$b.txt" "$i"
-    cabal run cpsa4 -- ${CPSAFLAGS} -o "$b.txt" "$i"
+    cabal run cpsa4 -v0 -- ${CPSAFLAGS} -o "$b.txt" "$i"
     echo cpsa4diff "$b.tst" "$b.txt"
-    cabal run cpsa4diff -- "$b.tst" "$b.txt"
+    cabal run cpsa4diff -v0 -- "$b.tst" "$b.txt"
     echo cpsa4graph -o "$b.xhtml" "$b.txt"
-    cabal run cpsa4graph -- -o "$b.xhtml" "$b.txt"
+    cabal run cpsa4graph -v0 -- -o "$b.xhtml" "$b.txt"
     echo cpsa4shapes -o "${b}_shapes.txt" "$b.txt"
-    cabal run cpsa4shapes -- -o "${b}_shapes.txt" "$b.txt"
+    cabal run cpsa4shapes -v0 -- -o "${b}_shapes.txt" "$b.txt"
     echo cpsa4graph -o "${b}_shapes.xhtml" "${b}_shapes.txt"
-    cabal run cpsa4graph -- -o "${b}_shapes.xhtml" "${b}_shapes.txt"
+    cabal run cpsa4graph -v0 -- -o "${b}_shapes.xhtml" "${b}_shapes.txt"
 done
